=== pieper/slicer2-nohistory/Base/tcl/mrml20.dtd
<!ELEMENT MRML (Transform | Volume | Model | TetraMesh | Color | Options | Fiducials)*>

<!ELEMENT Transform (Transform | Matrix | Volume | Model | Fiducials)*>

<!ELEMENT Point (#PCDATA)>
<!ATTLIST Point
    name NMTOKEN #REQUIRED
    xyz NMTOKENS "0.0 0.0 0.0"
    description CDATA "">

<!ELEMENT Fiducials (Point)*>

<!ELEMENT Matrix (#PCDATA)>
<!ATTLIST Matrix 
    name NMTOKEN "Matrix"
    description CDATA ""
    matrix NMTOKENS "1 0 0 0  0 1 0 0  0 0 1 0  0 0 0 1">

<!ELEMENT Volume (#PCDATA | Fiducials)>
<!ATTLIST Volume 
    name NMTOKEN ""
    filePattern CDATA "s.03d"
    filePrefix CDATA #REQUIRED
    dicomFileNameList CDATA ""
    rasToIjkMatrix NMTOKENS "1 0 0 0  0 1 0 0  0 0 1 0  0 0 0 1"
    rasToVtkMatrix NMTOKENS "1 0 0 0  0 -1 0 0  0 0 1 0  0 0 0 1"
    positionMatrix NMTOKENS "1 0 0 0  0 1 0 0  0 0 1 0  0 0 0 1"
    colorLUT NMTOKEN ""
    scanOrder (LR | RL | SI | IS | AP | PA) "SI"
    description CDATA ""
    scalarType (Char | UnsignedChar | Short | UnsignedShort | Int | UnsignedInt | Long | UnsignedLong | Float | Double) "Short"
    numScalars NMTOKEN "1"
    labelMap (yes | no) "no"
    interpolate (yes | no) "yes"
    littleEndian (yes | no) "no"
    tilt NMTOKEN "0.0"
    autoWindowLevel (yes | no) "yes"
    window CDATA "256"
    level CDATA "128"
    applyThreshold (yes | no) "no"
    autoThreshold (yes | no) "no"
    lowerThreshold CDATA "-32768"
    upperThreshold CDATA "32767"
    ignore (yes | no) "no"
    imageRange NMTOKENS "1 1"
    dimensions NMTOKENS "256 256"
    spacing NMTOKENS "1 1 1">

<!ELEMENT TetraMesh (#PCDATA | Fiducials)>
<!ATTLIST TetraMesh 
    name NMTOKEN ""
    fileName CDATA  #REQUIRED
    description CDATA ""
    Opacity NMTOKEN "1.0"
    Clipping (yes | no) "no"
    DisplaySurfaces (yes | no) "no"
      SurfacesUseCellData (yes | no) "yes"
    DisplayEdges    (yes | no) "no"
    DisplayNodes    (yes | no) "no"
      NodeScaling    NMTOKEN "9.5"
      NodeSkip       NMTOKEN "2"
    DisplayScalars  (yes | no) "no"
      ScalarScaling  NMTOKEN "9.5"
      ScalarSkip     NMTOKEN "2"
    DisplayVectors (yes | no) "no"
      VectorScaling  NMTOKEN "9.5"
      VectorSkip     NMTOKEN "2">

<!ELEMENT Model (#PCDATA | Fiducials)>
<!ATTLIST Model 
    name NMTOKEN ""
    fileName CDATA  #REQUIRED
    color NMTOKEN ""
    description CDATA ""
    opacity NMTOKEN "1.0"
    visibility (yes | no) "yes"
    clipping (yes | no) "no"
    backfaceCulling (yes | no) "yes"
    scalarVisibility (yes | no) "no"
    ignore (yes | no) "no"
    scalarRange NMTOKENS "0 100">

<!ELEMENT Color (#PCDATA)>
<!ATTLIST Color 
    name NMTOKEN #REQUIRED
    description CDATA ""
    diffuseColor NMTOKENS "1.0 1.0 1.0"
    ambient NMTOKEN "0.0"
    diffuse NMTOKEN "1.0"
    specular NMTOKEN "0.0"
    power NMTOKEN "1"
    labels NMTOKEN "">

<!ELEMENT Options (#PCDATA)>
<!ATTLIST Options 
    program CDATA #REQUIRED
    content CDATA "">

=== pieper/slicer2-nohistory/Modules/vtkRealignResample/Testing/TestInput/RealignResample.xml
<?xml version="1.0" standalone='no'?>
<!DOCTYPE MRML SYSTEM "mrml20.dtd">
<MRML>
<Transform name='transform0'>
  <Matrix name='manual0' matrix='1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1'></Matrix>
  <Volume id='V1' name='wcase1' filePattern='%s.%03d' filePrefix='../../../vtkAG/Testing/TestInput/strct/spgr/wcase1' rasToIjkMatrix='-1.06666667 0 0 127.5 0 0 -1.06666667 127.5 0 0.666666667 0 61.5 0 0 0 1' rasToVtkMatrix='-1.06666667 0 0 127.5 0 0 1.06666667 127.5 0 0.666666667 0 61.5 0 0 0 1' positionMatrix='-1 0 0 119.53125 0 0 1 -92.25 0 1 0 -119.53125 0 0 0 1' scanOrder='PA' description='PA' colorLUT='0' fullPrefix='/projects/schiz/strct/spd/women/filtered_spgr/wcase1/wcase1' window='174' level='91' lowerThreshold='0' upperThreshold='498' imageRange='0 123'></Volume>
</Transform>
<Fiducials name='midsag' type='default' symbolSize='6' textSize='6' visibility='1' color='0.4 1 1'>
  <Point name='midsag 0' index='0' xyz='0 0 72.1875' xyso='0 0 0 0' focalxyz='0 0 0' orientationwxyz='0 0 0 1'></Point>
  <Point name='midsag 1' index='1' xyz='-1.875 0 28.125' xyso='0 0 0 0' focalxyz='0 0 0' orientationwxyz='0 0 0 1'></Point>
  <Point name='midsag 2' index='2' xyz='-6.5625 0 9.375' xyso='0 0 0 0' focalxyz='0 0 0' orientationwxyz='0 0 0 1'></Point>
  <Point name='midsag 3' index='3' xyz='0.9375 -62 45' xyso='0 0 0 0' focalxyz='0 0 0' orientationwxyz='0 0 0 1'></Point>
  <Point name='midsag 4' index='4' xyz='-1.875 -62 21.5625' xyso='0 0 0 0' focalxyz='0 0 0' orientationwxyz='0 0 0 1'></Point>
  <Point name='midsag 5' index='5' xyz='-2.8125 -62 4.6875' xyso='0 0 0 0' focalxyz='0 0 0' orientationwxyz='0 0 0 1'></Point>
</Fiducials>
<Fiducials name='acpc' type='default' symbolSize='6' textSize='6' visibility='1' color='0.4 1 1'>
  <Point name='acpc 0' index='0' xyz='0 30 19.6875' xyso='0 0 0 0' focalxyz='0 0 0' orientationwxyz='0 0 0 1'></Point>
  <Point name='acpc 1' index='1' xyz='0 -23.4375 32.8125' xyso='0 0 0 0' focalxyz='0 0 0' orientationwxyz='0 0 0 1'></Point>
</Fiducials>
</MRML>

=== pieper/slicer2-nohistory/Doc/mrml/tutorial.xml
<?xml version="1.0" standalone='no'?>
<!DOCTYPE MRML SYSTEM "mrml20.dtd">
<MRML>
<Transform>
  <Matrix name='manual' matrix='1 0 0 -3 0 1 0 -12 0 0 1 28 0 0 0 1'></Matrix>
  <Volume name='SPGR' filePattern='%s.%03d' filePrefix='spgr/I' rasToIjkMatrix='0 -1.06667 0 142.187 0 0 -1.06667 98.1333 0.666667 0 0 59.9667 0 0 0 1' rasToVtkMatrix='0 -1.06667 0 142.187 0 0 1.06667 157.867 0.666667 0 0 59.9667 0 0 0 1' positionMatrix='0 0 1 -89.95 -1 0 0 133.3 0 1 0 -148 0 0 0 1' description='LR' colorLUT='0' window='146' level='76' applyThreshold='yes' lowerThreshold='17' upperThreshold='355' imageRange='1 124'></Volume>
</Transform>
<Volume name='all' filePattern='%s.%03d' filePrefix='labels/all' rasToIjkMatrix='0 -1.06667 0 128 0 0 -1.06667 128 0.666667 0 0 62 0 0 0 1' rasToVtkMatrix='0 -1.06667 0 128 0 0 1.06667 128 0.666667 0 0 62 0 0 0 1' positionMatrix='0 0 1 -93 -1 0 0 120 0 1 0 -120 0 0 0 1' description='LR' colorLUT='-1' labelMap='yes' interpolate='no' littleEndian='yes' window='4' level='1' lowerThreshold='0' upperThreshold='0' imageRange='1 124'></Volume>
<Model name='Skin' fileName='models/Skin.vtk' color='Skin' visibility='no'></Model>
<Model name='Ventricles' fileName='models/Ventricles.vtk' color='Ventricles' visibility='no'></Model>
<Model name='Vessels' fileName='models/Vessels.vtk' color='Vessels' visibility='no'></Model>
<Options program='slicer' content='presets'>
 View,0,viewUp='0 0 1 ' View,2,viewUp='0.367546 -0.233241 0.900282 ' View,3,viewUp='-0.442903 0.140948 0.885421 ' View,0,position='0 750 0 ' View,2,position='-383.298 227.108 215.322 ' View,3,position='358.357 -260.263 220.687 ' View,0,focalPoint='0 0 0 ' View,2,focalPoint='0 0 0 ' View,3,focalPoint='0 0 0 ' View,0,clippingRange='1 2001 ' View,2,clippingRange='0.659776 1320.21 ' View,3,clippingRange='0.659776 1320.21 ' View,2,viewBgColor='Black'
 Slices,2,opacity='0.3' Slices,3,opacity='0.0' Slices,2,0,visibility='1' Slices,3,0,visibility='1' Slices,2,0,backVolID='1' Slices,3,0,backVolID='1' Slices,2,0,foreVolID='2' Slices,2,0,labelVolID='2' Slices,3,0,labelVolID='2' Slices,2,1,visibility='1' Slices,3,1,visibility='1' Slices,2,1,backVolID='1' Slices,3,1,backVolID='1' Slices,2,1,foreVolID='2' Slices,2,1,labelVolID='2' Slices,3,1,labelVolID='2' Slices,2,2,visibility='1' Slices,3,2,visibility='1' Slices,2,2,backVolID='1' Slices,3,2,backVolID='1' Slices,2,2,foreVolID='2' Slices,2,2,labelVolID='2' Slices,3,2,labelVolID='2'
 Models,0,0,visibility='0' Models,2,0,visibility='0' Models,3,0,visibility='1' Models,0,0,opacity='1.0' Models,2,0,opacity='1.0' Models,3,0,opacity='1.0' Models,0,0,clipping='0' Models,2,0,clipping='0' Models,3,0,clipping='1' Models,0,0,backfaceCulling='1' Models,2,0,backfaceCulling='1' Models,3,0,backfaceCulling='0' Models,0,1,visibility='0' Models,2,1,visibility='0' Models,3,1,visibility='1' Models,0,1,opacity='1.0' Models,2,1,opacity='1.0' Models,3,1,opacity='1.0' Models,0,1,clipping='0' Models,2,1,clipping='0' Models,3,1,clipping='0' Models,0,1,backfaceCulling='1' Models,2,1,backfaceCulling='1' Models,3,1,backfaceCulling='1' Models,0,2,visibility='0' Models,2,2,visibility='0' Models,3,2,visibility='1' Models,0,2,opacity='1.0' Models,2,2,opacity='1.0' Models,3,2,opacity='1.0' Models,0,2,clipping='0' Models,2,2,clipping='0' Models,3,2,clipping='0' Models,0,2,backfaceCulling='1' Models,2,2,backfaceCulling='1' Models,3,2,backfaceCulling='1'
</Options>
</MRML>

=== pieper/slicer2-nohistory/Modules/vtkMIRIADSegment/tcl/colors_lobar.xml
<?xml version="1.0" standalone='no'?>
<!DOCTYPE MRML SYSTEM "mrml20.dtd">
<MRML>
<Color name='Unknown' diffuseColor='0 0 0' labels='0'></Color>
<Color name='Left-Frontal-Lobe' diffuseColor='1 0 0' labels='1'></Color>
<Color name='Left-Deep-Frontal-Lobe' diffuseColor='0 1 0' labels='2'></Color>
<Color name='Left-Parietal-Lobe' diffuseColor='1 1 0' labels='3'></Color>
<Color name='Left-Deep-Parietal-Lobe' diffuseColor='0 0 1' labels='4'></Color>
<Color name='Left-Temporal-Lobe' diffuseColor='1 0 1' labels='5'></Color>
<Color name='Left-Occipital-Lobe' diffuseColor='0 1 1' labels='6'></Color>
<Color name='Left-Cerebellum' diffuseColor='1 1 1' labels='7'></Color>
<Color name='Left-Brainstem' diffuseColor='0.5 1 0.5' labels='8'></Color>
<Color name='Right-Frontal-Lobe' diffuseColor='0.5 0 0' labels='11'></Color>
<Color name='Right-Deep-Frontal-Lobe' diffuseColor='0 0.5 0' labels='12'></Color>
<Color name='Right-Parietal-Lobe' diffuseColor='0.5 0.5 0' labels='13'></Color>
<Color name='Right-Deep-Parietal-Lobe' diffuseColor='0 0 0.5' labels='14'></Color>
<Color name='Right-Temporal-Lobe' diffuseColor='0.5 0 0.5' labels='15'></Color>
<Color name='Right-Occipital-Lobe' diffuseColor='0 0.5 0.5' labels='16'></Color>
<Color name='Right-Cerebellum' diffuseColor='0.5 0.5 0.5' labels='17'></Color>
<Color name='Right-Brainstem' diffuseColor='1 0.5 1' labels='18'></Color>
</MRML>

=== pieper/slicer2-nohistory/Base/tcl/Colors.xml
<?xml version="1.0" standalone='no'?>
<!DOCTYPE MRML SYSTEM "mrml20.dtd">
<MRML>
<Color name='Black' diffuseColor='0 0 0' labels='0'></Color>
<Color name='Skin' diffuseColor='1.0 .8 .7' labels='2'></Color>
<Color name='Brain' diffuseColor='1 1 1' labels='3'></Color>
<Color name='Ventricles' diffuseColor='.4 .7 1.0' labels='4'></Color>
<Color name='Vessels' diffuseColor='.9 .5 .5' labels='5'></Color>
<Color name='Tumor' diffuseColor='.5 .9 .5' labels='6'></Color>
<Color name='fMRI-high' diffuseColor='.5 .9 .9' labels='7'></Color>
<Color name='fMRI-low' diffuseColor='.9 .9 .5' labels='8'></Color>
<Color name='Pre-Gyrus' diffuseColor='.9 .7 .9' labels='9'></Color>
<Color name='Post-Gyrus' diffuseColor='.9 .9 .5' labels='10'></Color>
<Color name='jake' diffuseColor='.2 .5 .8' labels='11 21 31 41 51 61 71 81 91 101 111 121 131 141 151 161 171 181 191 201 211 221 231 241 251'></Color>
<Color name='elwood' diffuseColor='.2 .8 .5' labels='12 22 32 42 52 62 72 82 92 102 112 122 132 142 152 162 172 182 192 202 212 222 232 242 252'></Color>
<Color name='gato' diffuseColor='.8 .5 .2' labels='13 23 33 43 53 63 73 83 93 103 113 123 133 143 153 163 173 183 193 203 213 223 233 243 253'></Color>
<Color name='avery' diffuseColor='.8 .2 .5' labels='14 24 34 44 54 64 74 84 94 104 114 124 134 144 154 164 174 184 194 204 214 224 234 244 254'></Color>
<Color name='mambazo' diffuseColor='.5 .2 .8' labels='15 25 35 45 55 65 75 85 95 105 115 125 135 145 155 165 175 185 195 205 215 225 235 245 255'></Color>
<Color name='domino' diffuseColor='.5 .8 .2' labels='16 26 36 46 56 66 76 86 96 106 116 126 136 146 156 166 176 186 196 206 216 226 236 246 256'></Color>
<Color name='monk' diffuseColor='.2 .2 .8' labels='17 27 37 47 57 67 77 87 97 107 117 127 137 147 157 167 177 187 197 207 217 227 237 247'></Color>
<Color name='forest' diffuseColor='.8 .8 .2' labels='18 28 38 48 58 68 78 88 98 108 118 128 138 148 158 168 178 188 198 208 218 228 238 248'></Color>
<Color name='dylan' diffuseColor='.2 .8 .8' labels='19 29 39 49 59 69 79 89 99 109 119 129 139 149 159 169 179 189 199 209 219 229 239 249'></Color>
<Color name='kales' diffuseColor='.5 .5 .5' labels='20 30 40 50 60 70 80 90 100 110 120 130 140 150 160 170 180 190 200 210 220 230 240 250'></Color>
<Color name='fMRI-neg' diffuseColor='0 .8 1.0' labels='300'></Color>
<Color name='fMRI-pos' diffuseColor='1.0 1.0 0' labels='301'></Color>
</MRML>
